### ISSUE TITLE
Submitted bathroom showing up incorrectly on homepage

### ISSUE THREAD

**Issue by Jricecake** [mason-lynass/bbb-react-supabase#25]
A bathroom I reported last night has seemingly been approved, but shows up incorrectly under the "most recent review" section.
Harry's Fine Foods title is correct, but link and info point to a Hellbent Brewery review.

![BBBissue](https://github.com/mason-lynass/bbb-react-supabase/assets/46724048/d6abfb0f-5e77-40f0-9a04-bc6662747611)

**Comment by mason-lynass** [comment]
fixed this in PR #26  - I used '=' instead of '===' ....
